/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class IT extends javax.swing.JFrame {

    /**
     * Creates new form IT
     */
    public IT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton17 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        backBTN = new javax.swing.JButton();
        Exitbtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        IT2123 = new javax.swing.JButton();
        IT02221 = new javax.swing.JButton();
        IT02230 = new javax.swing.JButton();
        IT02244 = new javax.swing.JButton();
        IT02205 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        IT02122 = new javax.swing.JButton();
        IT02123 = new javax.swing.JButton();
        IT02125 = new javax.swing.JButton();
        IT01204 = new javax.swing.JButton();
        IT01205 = new javax.swing.JButton();
        jLayeredPane5 = new javax.swing.JLayeredPane();
        IT1202 = new javax.swing.JButton();
        IT01202 = new javax.swing.JButton();
        IT1204 = new javax.swing.JButton();
        IT1205 = new javax.swing.JButton();
        IT1206 = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        IT01123 = new javax.swing.JButton();
        IT01124 = new javax.swing.JButton();
        IT01125 = new javax.swing.JButton();
        IT01126 = new javax.swing.JButton();
        IT01127 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jButton17.setText("jButton6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBTN.setText("Back");
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });
        jPanel1.add(backBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, -1, -1));

        Exitbtn.setText("Exit");
        Exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitbtnActionPerformed(evt);
            }
        });
        jPanel1.add(Exitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel4.setText("Year 2st Semester 1");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 140, 154, 41));

        jButton1.setText("Next Page");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 590, -1, -1));

        jPanel2.setBackground(new java.awt.Color(41, 122, 165));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        IT2123.setText("IT02210");
        IT2123.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IT2123ActionPerformed(evt);
            }
        });

        IT02221.setText("IT02221");

        IT02230.setText("IT02230");

        IT02244.setText("IT02244");

        IT02205.setText("IT02205");

        jLayeredPane3.setLayer(IT2123, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(IT02221, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(IT02230, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(IT02244, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(IT02205, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IT02221, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(IT2123, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(IT02230, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane3Layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(IT02244, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(IT02205, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(16, Short.MAX_VALUE)))
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(IT2123, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(IT02221, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(IT02230, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane3Layout.createSequentialGroup()
                    .addContainerGap(207, Short.MAX_VALUE)
                    .addComponent(IT02244, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(IT02205, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(32, 32, 32)))
        );

        jPanel2.add(jLayeredPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel2.setText("Year 1st Semester 1");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 154, 41));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel5.setText("Year 2st Semester 2");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, 154, 33));

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        IT02122.setText("IT02122");
        IT02122.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IT02122ActionPerformed(evt);
            }
        });

        IT02123.setText("IT02123");
        IT02123.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IT02123ActionPerformed(evt);
            }
        });

        IT02125.setText("IT02125");

        IT01204.setText("IT02126");

        IT01205.setText("IT02128");

        jLayeredPane2.setLayer(IT02122, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(IT02123, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(IT02125, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(IT01204, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(IT01205, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(IT02122, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(IT02123, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(IT02125, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(IT01204, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(IT01205, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(16, Short.MAX_VALUE)))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(IT02122, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(IT02123, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(IT02125, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addContainerGap(207, Short.MAX_VALUE)
                    .addComponent(IT01204, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(IT01205, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(32, 32, 32)))
        );

        jPanel2.add(jLayeredPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, -1, -1));

        jLayeredPane5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        IT1202.setText("IT01201");
        IT1202.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IT1202ActionPerformed(evt);
            }
        });

        IT01202.setText("IT01202");

        IT1204.setText("IT01203");

        IT1205.setText("IT01204");

        IT1206.setText("IT01205");

        jLayeredPane5.setLayer(IT1202, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(IT01202, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(IT1204, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(IT1205, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(IT1206, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane5Layout = new javax.swing.GroupLayout(jLayeredPane5);
        jLayeredPane5.setLayout(jLayeredPane5Layout);
        jLayeredPane5Layout.setHorizontalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IT01202, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(IT1202, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(IT1204, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane5Layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(IT1205, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(IT1206, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(16, Short.MAX_VALUE)))
        );
        jLayeredPane5Layout.setVerticalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(IT1202, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(IT01202, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(IT1204, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(161, Short.MAX_VALUE))
            .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane5Layout.createSequentialGroup()
                    .addContainerGap(208, Short.MAX_VALUE)
                    .addComponent(IT1205, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(IT1206, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(32, 32, 32)))
        );

        jPanel2.add(jLayeredPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, -1));

        jLayeredPane1.setBackground(new java.awt.Color(129, 207, 255));
        jLayeredPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        IT01123.setText("IT01123");
        IT01123.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IT01123ActionPerformed(evt);
            }
        });

        IT01124.setText("IT01124");
        IT01124.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IT01124ActionPerformed(evt);
            }
        });

        IT01125.setText("IT01125");
        IT01125.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IT01125ActionPerformed(evt);
            }
        });

        IT01126.setText("IT01126");
        IT01126.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IT01126ActionPerformed(evt);
            }
        });

        IT01127.setText("IT01127");
        IT01127.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IT01127ActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(IT01123, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(IT01124, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(IT01125, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(IT01126, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(IT01127, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(IT01126, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(IT01124, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(IT01127, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(IT01125, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(IT01123, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(13, Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(IT01123, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(IT01124, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(IT01125, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(IT01126, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(IT01127, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(33, Short.MAX_VALUE)))
        );

        jPanel2.add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setText("Year 1st Semester 2");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 154, 41));

        jPanel3.setBackground(new java.awt.Color(206, 225, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 770, 430));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Information Technology");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 235, 48));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitbtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitbtnActionPerformed

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        // TODO add your handling code here:
        courses obj = new courses();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBTNActionPerformed

    private void IT02122ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IT02122ActionPerformed
        // TODO add your handling code here:
        try{
           File file = new File("C:\\xampp\\mysql\\data\\pds2\\pdffiles\\IT02122.pdf");
            
            if (file.exists()){
                if(Desktop.isDesktopSupported()){
                    Desktop.getDesktop().open(file);
                }
                else{
                    JOptionPane.showMessageDialog(this,"Not Supported");
                }
            }
            else{
                JOptionPane.showMessageDialog(this,"File not Exist");
            }
        }catch(IOException e){
            JOptionPane.showMessageDialog(this, "An error occurred while trying to open the file.");
        
        e.printStackTrace();}
        
    }//GEN-LAST:event_IT02122ActionPerformed

    private void IT01123ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IT01123ActionPerformed
        // TODO add your handling code here:
        try{
           File file = new File("C:\\xampp\\mysql\\data\\pds2\\pdffiles\\IT01123.pdf");
            
            if (file.exists()){
                if(Desktop.isDesktopSupported()){
                    Desktop.getDesktop().open(file);
                }
                else{
                    JOptionPane.showMessageDialog(this,"Not Supported");
                }
            }
            else{
                JOptionPane.showMessageDialog(this,"File not Exist");
            }
        }catch(IOException e){
            JOptionPane.showMessageDialog(this, "An error occurred while trying to open the file.");
        
        e.printStackTrace();}
    }//GEN-LAST:event_IT01123ActionPerformed

    private void IT01124ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IT01124ActionPerformed
        // TODO add your handling code here:
        try{
           File file = new File("C:\\xampp\\mysql\\data\\pds2\\pdffiles\\IT01124.pdf");
            
            if (file.exists()){
                if(Desktop.isDesktopSupported()){
                    Desktop.getDesktop().open(file);
                }
                else{
                    JOptionPane.showMessageDialog(this,"Not Supported");
                }
            }
            else{
                JOptionPane.showMessageDialog(this,"File not Exist");
            }
        }catch(IOException e){
            JOptionPane.showMessageDialog(this, "An error occurred while trying to open the file.");
        
        e.printStackTrace();}
    }//GEN-LAST:event_IT01124ActionPerformed

    private void IT01125ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IT01125ActionPerformed
        // TODO add your handling code here:
        try{
           File file = new File("C:\\xampp\\mysql\\data\\pds2\\pdffiles\\IT01125.pdf");
            
            if (file.exists()){
                if(Desktop.isDesktopSupported()){
                    Desktop.getDesktop().open(file);
                }
                else{
                    JOptionPane.showMessageDialog(this,"Not Supported");
                }
            }
            else{
                JOptionPane.showMessageDialog(this,"File not Exist");
            }
        }catch(IOException e){
            JOptionPane.showMessageDialog(this, "An error occurred while trying to open the file.");
        
        e.printStackTrace();}
        
    }//GEN-LAST:event_IT01125ActionPerformed

    private void IT01126ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IT01126ActionPerformed
        // TODO add your handling code here:
        try{
           File file = new File("C:\\xampp\\mysql\\data\\pds2\\pdffiles\\IT01126.pdf");
            
            if (file.exists()){
                if(Desktop.isDesktopSupported()){
                    Desktop.getDesktop().open(file);
                }
                else{
                    JOptionPane.showMessageDialog(this,"Not Supported");
                }
            }
            else{
                JOptionPane.showMessageDialog(this,"File not Exist");
            }
        }catch(IOException e){
            JOptionPane.showMessageDialog(this, "An error occurred while trying to open the file.");
        
        e.printStackTrace();}
    }//GEN-LAST:event_IT01126ActionPerformed

    private void IT01127ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IT01127ActionPerformed
        // TODO add your handling code here:
        try{
           File file = new File("C:\\xampp\\mysql\\data\\pds2\\pdffiles\\IT01127.pdf");
            
            if (file.exists()){
                if(Desktop.isDesktopSupported()){
                    Desktop.getDesktop().open(file);
                }
                else{
                    JOptionPane.showMessageDialog(this,"Not Supported");
                }
            }
            else{
                JOptionPane.showMessageDialog(this,"File not Exist");
            }
        }catch(IOException e){
            JOptionPane.showMessageDialog(this, "An error occurred while trying to open the file.");
        
        e.printStackTrace();}
    }//GEN-LAST:event_IT01127ActionPerformed

    private void IT1202ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IT1202ActionPerformed
        // TODO add your handling code here:
        try{
           File file = new File("C:\\xampp\\mysql\\data\\pds2\\pdffiles\\IT1202.pdf");
            
            if (file.exists()){
                if(Desktop.isDesktopSupported()){
                    Desktop.getDesktop().open(file);
                }
                else{
                    JOptionPane.showMessageDialog(this,"Not Supported");
                }
            }
            else{
                JOptionPane.showMessageDialog(this,"File not Exist");
            }
        }catch(IOException e){
            JOptionPane.showMessageDialog(this, "An error occurred while trying to open the file.");
        
        e.printStackTrace();}
    }//GEN-LAST:event_IT1202ActionPerformed

    private void IT2123ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IT2123ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_IT2123ActionPerformed

    private void IT02123ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IT02123ActionPerformed
        // TODO add your handling code here:
        try{
           File file = new File("C:\\xampp\\mysql\\data\\pds2\\pdffiles\\IT02123.pdf");
            
            if (file.exists()){
                if(Desktop.isDesktopSupported()){
                    Desktop.getDesktop().open(file);
                }
                else{
                    JOptionPane.showMessageDialog(this,"Not Supported");
                }
            }
            else{
                JOptionPane.showMessageDialog(this,"File not Exist");
            }
        }catch(IOException e){
            JOptionPane.showMessageDialog(this, "An error occurred while trying to open the file.");
        
        e.printStackTrace();}
    }//GEN-LAST:event_IT02123ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exitbtn;
    private javax.swing.JButton IT01123;
    private javax.swing.JButton IT01124;
    private javax.swing.JButton IT01125;
    private javax.swing.JButton IT01126;
    private javax.swing.JButton IT01127;
    private javax.swing.JButton IT01202;
    private javax.swing.JButton IT01204;
    private javax.swing.JButton IT01205;
    private javax.swing.JButton IT02122;
    private javax.swing.JButton IT02123;
    private javax.swing.JButton IT02125;
    private javax.swing.JButton IT02205;
    private javax.swing.JButton IT02221;
    private javax.swing.JButton IT02230;
    private javax.swing.JButton IT02244;
    private javax.swing.JButton IT1202;
    private javax.swing.JButton IT1204;
    private javax.swing.JButton IT1205;
    private javax.swing.JButton IT1206;
    private javax.swing.JButton IT2123;
    private javax.swing.JButton backBTN;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton17;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
